import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "NIOVA | AI Agent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        
        <ClerkProvider>
          {/* header */}
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          {/* footer */}
          <footer className="bg-blue-100 py-12">
            <div className="container mx-auto px-4 text-center ">
              <p>Designed & Developed By Vinit Jain</p>
            </div>
          </footer>
        </ClerkProvider>

      </body>
    </html>
  );
}
